"""Server-rendered HTML printable documents using Jinja2."""

from jinja2 import Template

from app.core.exceptions import InvalidOperationStatusError
from app.models import Delivery, Receipt
from app.utils.enums import OperationStatus

RECEIPT_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Receipt - {{ receipt.reference }}</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; margin: 40px; color: #222; }
        .header { border-bottom: 2px solid #333; padding-bottom: 12px; margin-bottom: 24px; display: flex; justify-content: space-between; align-items: flex-end; }
        .title { font-size: 24px; font-weight: bold; margin: 0; }
        .meta { margin-bottom: 24px; }
        .meta-table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        .meta-table td { padding: 6px 12px; vertical-align: top; }
        .meta-table td.label { font-weight: bold; width: 180px; color: #555; }
        .status-badge { display: inline-block; background-color: #28a745; color: white; padding: 4px 10px; border-radius: 4px; font-weight: bold; font-size: 13px; }
        table.items { width: 100%; border-collapse: collapse; margin-top: 16px; margin-bottom: 30px; }
        table.items th, table.items td { border: 1px solid #ddd; padding: 10px 12px; text-align: left; }
        table.items th { background-color: #f7f7f7; font-weight: 600; }
        table.items td.num { text-align: right; }
        .footer { margin-top: 40px; border-top: 1px dashed #ccc; padding-top: 16px; font-size: 12px; color: #777; display: flex; justify-content: space-between; }
        @media print {
            body { margin: 10mm; }
            .no-print { display: none; }
        }
    </style>
</head>
<body>
    <div class="header">
        <div>
            <h1 class="title">StockSense — Goods Receipt Note</h1>
            <p style="margin: 4px 0 0 0; color: #666;">Warehouse Inventory Management</p>
        </div>
        <div>
            <span class="status-badge">{{ receipt.status }}</span>
        </div>
    </div>

    <table class="meta-table">
        <tr>
            <td class="label">Reference:</td>
            <td><strong>{{ receipt.reference }}</strong></td>
            <td class="label">Destination:</td>
            <td>{{ destination_name }} ({{ destination_code }})</td>
        </tr>
        <tr>
            <td class="label">Supplier:</td>
            <td>{{ receipt.supplier_name }}</td>
            <td class="label">Completed Date:</td>
            <td>{{ receipt.updated_at }}</td>
        </tr>
        <tr>
            <td class="label">Scheduled Date:</td>
            <td>{{ receipt.scheduled_date or "N/A" }}</td>
            <td class="label">Created Date:</td>
            <td>{{ receipt.created_at }}</td>
        </tr>
    </table>

    <h3>Received Items</h3>
    <table class="items">
        <thead>
            <tr>
                <th style="width: 50px;">#</th>
                <th>SKU</th>
                <th>Product Name</th>
                <th>UoM</th>
                <th class="num">Quantity</th>
            </tr>
        </thead>
        <tbody>
            {% for item in items %}
            <tr>
                <td>{{ loop.index }}</td>
                <td>{{ item.sku }}</td>
                <td>{{ item.name }}</td>
                <td>{{ item.uom }}</td>
                <td class="num">{{ item.quantity }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <div class="footer">
        <div>Document generated by StockSense API</div>
        <div>Authorized Signature: _______________________</div>
    </div>
</body>
</html>
"""

DELIVERY_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delivery - {{ delivery.reference }}</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; margin: 40px; color: #222; }
        .header { border-bottom: 2px solid #333; padding-bottom: 12px; margin-bottom: 24px; display: flex; justify-content: space-between; align-items: flex-end; }
        .title { font-size: 24px; font-weight: bold; margin: 0; }
        .meta-table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        .meta-table td { padding: 6px 12px; vertical-align: top; }
        .meta-table td.label { font-weight: bold; width: 180px; color: #555; }
        .status-badge { display: inline-block; background-color: #28a745; color: white; padding: 4px 10px; border-radius: 4px; font-weight: bold; font-size: 13px; }
        table.items { width: 100%; border-collapse: collapse; margin-top: 16px; margin-bottom: 30px; }
        table.items th, table.items td { border: 1px solid #ddd; padding: 10px 12px; text-align: left; }
        table.items th { background-color: #f7f7f7; font-weight: 600; }
        table.items td.num { text-align: right; }
        .footer { margin-top: 40px; border-top: 1px dashed #ccc; padding-top: 16px; font-size: 12px; color: #777; display: flex; justify-content: space-between; }
        @media print {
            body { margin: 10mm; }
            .no-print { display: none; }
        }
    </style>
</head>
<body>
    <div class="header">
        <div>
            <h1 class="title">StockSense — Delivery Note / Outward Slip</h1>
            <p style="margin: 4px 0 0 0; color: #666;">Warehouse Inventory Management</p>
        </div>
        <div>
            <span class="status-badge">{{ delivery.status }}</span>
        </div>
    </div>

    <table class="meta-table">
        <tr>
            <td class="label">Reference:</td>
            <td><strong>{{ delivery.reference }}</strong></td>
            <td class="label">Source Location:</td>
            <td>{{ source_name }} ({{ source_code }})</td>
        </tr>
        <tr>
            <td class="label">Customer:</td>
            <td>{{ delivery.customer_name }}</td>
            <td class="label">Dispatched Date:</td>
            <td>{{ delivery.updated_at }}</td>
        </tr>
        <tr>
            <td class="label">Scheduled Date:</td>
            <td>{{ delivery.scheduled_date or "N/A" }}</td>
            <td class="label">Created Date:</td>
            <td>{{ delivery.created_at }}</td>
        </tr>
    </table>

    <h3>Delivered Items</h3>
    <table class="items">
        <thead>
            <tr>
                <th style="width: 50px;">#</th>
                <th>SKU</th>
                <th>Product Name</th>
                <th>UoM</th>
                <th class="num">Quantity</th>
            </tr>
        </thead>
        <tbody>
            {% for item in items %}
            <tr>
                <td>{{ loop.index }}</td>
                <td>{{ item.sku }}</td>
                <td>{{ item.name }}</td>
                <td>{{ item.uom }}</td>
                <td class="num">{{ item.quantity }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <div class="footer">
        <div>Document generated by StockSense API</div>
        <div>Received by (Customer Signature): _______________________</div>
    </div>
</body>
</html>
"""


class PrintService:
    @staticmethod
    def render_receipt(receipt: Receipt) -> str:
        if receipt.status != OperationStatus.DONE:
            raise InvalidOperationStatusError(
                f"Receipt {receipt.reference} cannot be printed unless status is DONE (current: {receipt.status})"
            )
        template = Template(RECEIPT_HTML_TEMPLATE)
        items_data = [
            {
                "sku": item.product.sku if item.product else "",
                "name": item.product.name if item.product else "",
                "uom": item.product.unit_of_measure.value if (item.product and hasattr(item.product.unit_of_measure, "value")) else str(item.product.unit_of_measure if item.product else ""),
                "quantity": f"{item.quantity:.3f}",
            }
            for item in receipt.items
        ]
        dest_name = receipt.destination_location.name if receipt.destination_location else "N/A"
        dest_code = receipt.destination_location.code if receipt.destination_location else "N/A"
        return template.render(
            receipt=receipt,
            items=items_data,
            destination_name=dest_name,
            destination_code=dest_code,
        )

    @staticmethod
    def render_delivery(delivery: Delivery) -> str:
        if delivery.status != OperationStatus.DONE:
            raise InvalidOperationStatusError(
                f"Delivery {delivery.reference} cannot be printed unless status is DONE (current: {delivery.status})"
            )
        template = Template(DELIVERY_HTML_TEMPLATE)
        items_data = [
            {
                "sku": item.product.sku if item.product else "",
                "name": item.product.name if item.product else "",
                "uom": item.product.unit_of_measure.value if (item.product and hasattr(item.product.unit_of_measure, "value")) else str(item.product.unit_of_measure if item.product else ""),
                "quantity": f"{item.quantity:.3f}",
            }
            for item in delivery.items
        ]
        source_name = delivery.source_location.name if delivery.source_location else "N/A"
        source_code = delivery.source_location.code if delivery.source_location else "N/A"
        return template.render(
            delivery=delivery,
            items=items_data,
            source_name=source_name,
            source_code=source_code,
        )


print_service = PrintService()
