-- All result sets headed PASS must be empty; row counts document the demo fixture.
SELECT 'users' entity, count(*) rows FROM users UNION ALL SELECT 'categories',count(*) FROM categories UNION ALL SELECT 'products',count(*) FROM products UNION ALL SELECT 'warehouses',count(*) FROM warehouses UNION ALL SELECT 'locations',count(*) FROM locations UNION ALL SELECT 'inventory',count(*) FROM inventory UNION ALL SELECT 'receipts',count(*) FROM receipts UNION ALL SELECT 'receipt_items',count(*) FROM receipt_items UNION ALL SELECT 'deliveries',count(*) FROM deliveries UNION ALL SELECT 'delivery_items',count(*) FROM delivery_items UNION ALL SELECT 'transfers',count(*) FROM transfers UNION ALL SELECT 'transfer_items',count(*) FROM transfer_items UNION ALL SELECT 'adjustments',count(*) FROM adjustments UNION ALL SELECT 'stock_ledger',count(*) FROM stock_ledger ORDER BY entity;
SELECT 'FAIL: duplicate SKU' check_name, sku, count(*) FROM products GROUP BY sku HAVING count(*) > 1;
SELECT 'FAIL: duplicate operation reference' check_name, reference, count(*) FROM (SELECT reference FROM receipts UNION ALL SELECT reference FROM deliveries UNION ALL SELECT reference FROM transfers UNION ALL SELECT reference FROM adjustments) operation_references GROUP BY reference HAVING count(*) > 1;
SELECT 'FAIL: orphan inventory relation' check_name, i.id FROM inventory i LEFT JOIN products p ON p.id=i.product_id LEFT JOIN locations l ON l.id=i.location_id WHERE p.id IS NULL OR l.id IS NULL;
SELECT 'FAIL: orphan operation relation' check_name, x.id FROM (SELECT id,created_by FROM receipts UNION ALL SELECT id,created_by FROM deliveries UNION ALL SELECT id,created_by FROM transfers UNION ALL SELECT id,created_by FROM adjustments) x LEFT JOIN users u ON u.id=x.created_by WHERE u.id IS NULL;
SELECT 'FAIL: invalid operation status' check_name, reference, status FROM (SELECT reference,status FROM receipts UNION ALL SELECT reference,status FROM deliveries UNION ALL SELECT reference,status FROM transfers UNION ALL SELECT reference,status FROM adjustments) operations WHERE status NOT IN ('DRAFT','WAITING','READY','DONE','CANCELED');
SELECT 'FAIL: inventory bounds' check_name, * FROM inventory WHERE on_hand < 0 OR reserved < 0 OR reserved > on_hand;
SELECT 'FAIL: inventory != ledger' check_name, i.product_id,i.location_id,i.on_hand,COALESCE(SUM(CASE WHEN l.destination_location_id=i.location_id THEN l.quantity ELSE 0 END),0)+COALESCE(SUM(CASE WHEN l.source_location_id=i.location_id THEN l.quantity ELSE 0 END),0) ledger_total FROM inventory i LEFT JOIN stock_ledger l ON l.product_id=i.product_id AND (l.destination_location_id=i.location_id OR l.source_location_id=i.location_id) GROUP BY i.product_id,i.location_id,i.on_hand HAVING i.on_hand <> COALESCE(SUM(CASE WHEN l.destination_location_id=i.location_id THEN l.quantity ELSE 0 END),0)+COALESCE(SUM(CASE WHEN l.source_location_id=i.location_id THEN l.quantity ELSE 0 END),0);
SELECT 'FAIL: transfer is not conserved' check_name, reference_id, SUM(quantity) FROM stock_ledger WHERE movement_type IN ('TRANSFER_OUT','TRANSFER_IN') GROUP BY reference_id HAVING SUM(quantity) <> 0;
SELECT 'FAIL: adjustment difference' check_name, reference FROM adjustments WHERE difference <> physical_quantity-system_quantity;
SELECT 'FAIL: inventory missing opening ledger' check_name, i.product_id,i.location_id FROM inventory i WHERE NOT EXISTS (SELECT 1 FROM stock_ledger l WHERE l.product_id=i.product_id AND l.destination_location_id=i.location_id AND l.movement_type='INITIAL_STOCK');
SELECT 'FAIL: done document ledger mismatch' check_name, d.reference FROM (SELECT reference,id,'receipt' kind FROM receipts WHERE status='DONE' UNION ALL SELECT reference,id,'delivery' FROM deliveries WHERE status='DONE' UNION ALL SELECT reference,id,'transfer' FROM transfers WHERE status='DONE' UNION ALL SELECT reference,id,'adjustment' FROM adjustments WHERE status='DONE') d WHERE NOT EXISTS (SELECT 1 FROM stock_ledger l WHERE l.reference_id=d.id AND l.reference_type=d.kind);
SELECT 'FAIL: non-done document has ledger' check_name, l.reference_type,l.reference_id FROM stock_ledger l LEFT JOIN receipts r ON l.reference_type='receipt' AND l.reference_id=r.id LEFT JOIN deliveries d ON l.reference_type='delivery' AND l.reference_id=d.id LEFT JOIN transfers t ON l.reference_type='transfer' AND l.reference_id=t.id LEFT JOIN adjustments a ON l.reference_type='adjustment' AND l.reference_id=a.id WHERE (r.id IS NOT NULL AND r.status <> 'DONE') OR (d.id IS NOT NULL AND d.status <> 'DONE') OR (t.id IS NOT NULL AND t.status <> 'DONE') OR (a.id IS NOT NULL AND a.status <> 'DONE');
SELECT p.sku,p.name,COALESCE(SUM(i.on_hand),0) on_hand,COALESCE(SUM(i.on_hand-i.reserved),0) free_to_use,p.reorder_level,CASE WHEN COALESCE(SUM(i.on_hand),0)=0 THEN 'OUT_OF_STOCK' WHEN COALESCE(SUM(i.on_hand),0)<=p.reorder_level THEN 'LOW_STOCK' ELSE 'HEALTHY' END stock_status FROM products p LEFT JOIN inventory i ON i.product_id=p.id GROUP BY p.id ORDER BY p.sku;
